name: latex-docker

services:
  texlive:
    container_name: latex-docker-texlive
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/workdir
    tty: true
    restart: always

